//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOT
    {
        public int ID { get; set; }
        public int MID_ID { get; set; }
        public int TOP_ID { get; set; }
    }
}
